import React, { useMemo, useState, useRef, useEffect } from 'react';
import { View, Text, TouchableOpacity, Modal, Alert, StyleSheet, Dimensions } from 'react-native';
import { MaterialIcons } from '@expo/vector-icons';
import { WebView } from 'react-native-webview';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import * as FileSystem from 'expo-file-system/legacy';
import * as MediaLibrary from 'expo-media-library';
import { useStore } from '../store/useStore';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default function BarcodeModal({ visible, onClose, item }) {
  const profile = useStore(state => state.profile);
  const [base64Image, setBase64Image] = useState(null);
  const [isReady, setIsReady] = useState(false);
  
  const rawId = item?.sku || item?.id || '000000';
  const barcodeValue = rawId.toString().replace(/[^a-zA-Z0-9\-\.]/g, '-');

  useEffect(() => {
    if (visible) {
      setIsReady(false);
      setBase64Image(null);
    }
  }, [visible, item?.id]);

  const htmlContent = useMemo(() => `
    <!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.0/dist/JsBarcode.all.min.js"></script>
        <style>
          body { display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; background: white; overflow: hidden; }
          #barcode { width: 100%; height: auto; }
        </style>
      </head>
      <body>
        <canvas id="barcode"></canvas>
        <script>
          function generate() {
            try {
              JsBarcode("#barcode", "${barcodeValue}", {
                format: "CODE128",
                width: 4,
                height: 100,
                displayValue: false,
                margin: 20
              });
              setTimeout(() => {
                const canvas = document.getElementById('barcode');
                const dataUrl = canvas.toDataURL("image/png");
                window.ReactNativeWebView.postMessage(JSON.stringify({
                  type: 'BARCODE_READY',
                  data: dataUrl
                }));
              }, 1000);
            } catch(e) {
              window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'ERROR', message: e.message }));
            }
          }
          if (typeof JsBarcode === 'function') generate();
          else window.onload = generate;
        </script>
      </body>
    </html>
  `, [barcodeValue]);

  if (!item) return null;

  const onMessage = (event) => {
    try {
      const message = JSON.parse(event.nativeEvent.data);
      if (message.type === 'BARCODE_READY') {
        setBase64Image(message.data);
        setIsReady(true);
      }
    } catch (e) {
      const dataUrl = event.nativeEvent.data;
      if (dataUrl && dataUrl.startsWith('data:image/png;base64,')) {
        setBase64Image(dataUrl);
        setIsReady(true);
      }
    }
  };

  const handleDownloadPDF = async () => {
    if (!isReady || !base64Image) {
      Alert.alert('Please Wait', 'Barcode is still being generated.');
      return;
    }

    try {
      const html = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #272756; text-align: center; }
              .container { border: 2px solid #e2e8f0; border-radius: 20px; padding: 40px; display: inline-block; background: white; width: 400px; }
              .item-name { font-size: 24px; font-weight: bold; margin-bottom: 20px; }
              .barcode-img { width: 100%; height: auto; margin: 20px 0; }
              .item-price { font-size: 32px; font-weight: 900; color: #ec5b13; margin-top: 20px; }
              .sku { font-size: 16px; color: #64748b; margin-top: 10px; }
              .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="item-name">${item.name}</div>
              <img src="${base64Image}" class="barcode-img" />
              <div class="sku">${barcodeValue}</div>
              <div class="item-price">${profile.currency_symbol || '$'}${(item.retail_price || item.price || 0).toFixed(2)}</div>
            </div>
            <div class="footer">Generated by Zoxm Invoice</div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri);
    } catch (error) {
      Alert.alert('Error', 'PDF Download Failed: ' + error.message);
    }
  };

  const handleDownloadImage = async () => {
    if (!isReady || !base64Image) {
      Alert.alert('Please Wait', 'Barcode image is still being prepared...');
      return;
    }

    try {
      // Request permissions
      const { status } = await MediaLibrary.requestPermissionsAsync();
      if (status !== 'granted') {
        Alert.alert(
          'Permission Denied',
          'Storage permission is required to save the barcode to your gallery.',
          [{ text: 'OK' }]
        );
        return;
      }

      // Strip data URI prefix if present
      const base64Data = base64Image.replace(/^data:image\/\w+;base64,/, '');
      
      // Use timestamp to ensure unique filename
      const timestamp = Date.now();
      const safeId = String(item?.id || item?.sku || 'barcode').replace(/[^a-zA-Z0-9]/g, '_');
      const filename = `${FileSystem.cacheDirectory}barcode_${safeId}_${timestamp}.png`;

      await FileSystem.writeAsStringAsync(filename, base64Data, {
        encoding: 'base64',
      });

      const asset = await MediaLibrary.createAssetAsync(filename);
      
      try {
        await MediaLibrary.createAlbumAsync('Zoxm Barcodes', asset, false);
      } catch (albumErr) {
        // Album may already exist on some Android versions — ignore
        console.log('Album note:', albumErr.message);
      }

      Alert.alert('✅ Saved!', 'Barcode saved to your Gallery in the "Zoxm Barcodes" album.');
    } catch (error) {
      Alert.alert('Error', 'Failed to save barcode: ' + error.message);
    }
  };

  return (
    <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <View style={styles.overlay}>
        <View style={styles.modalContent}>
          <View style={styles.header}>
            <Text style={styles.headerTitle}>Item Barcode</Text>
            <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
              <MaterialIcons name="close" size={20} color="#64748b" />
            </TouchableOpacity>
          </View>

          <View style={styles.barcodeWrapper}>
            <View style={styles.webviewContainer}>
              <WebView
                originWhitelist={['*']}
                source={{ html: htmlContent }}
                style={styles.webview}
                scrollEnabled={false}
                backgroundColor="transparent"
                onMessage={onMessage}
                javaScriptEnabled={true}
              />
            </View>
            <Text style={styles.barcodeText}>{barcodeValue}</Text>
            {!isReady && <Text style={styles.loadingText}>Generating...</Text>}
          </View>

          <View style={styles.detailsContainer}>
            <Text style={styles.itemName}>{item.name}</Text>
            {item.sku ? (
              <View style={styles.skuBadge}>
                <MaterialIcons name="view-stream" size={14} color="#64748b" />
                <Text style={styles.skuText}>SKU: {item.sku}</Text>
              </View>
            ) : null}
            <Text style={styles.priceText}>
              {profile.currency_symbol || '$'}{(item.retail_price || item.price || 0).toFixed(2)}
            </Text>
          </View>

          <View style={styles.actionsContainer}>
            <View style={styles.btnRow}>
              <TouchableOpacity 
                onPress={handleDownloadImage} 
                style={[styles.btn, styles.imageBtn, !isReady && styles.disabledBtn]}
                disabled={!isReady}
              >
                <MaterialIcons name="image" size={18} color="white" />
                <Text style={styles.btnLabel}>Download Image</Text>
              </TouchableOpacity>
              <TouchableOpacity 
                onPress={handleDownloadPDF} 
                style={[styles.btn, styles.pdfBtn, !isReady && styles.disabledBtn]}
                disabled={!isReady}
              >
                <MaterialIcons name="picture-as-pdf" size={18} color="white" />
                <Text style={styles.btnLabel}>Download PDF</Text>
              </TouchableOpacity>
            </View>
            <TouchableOpacity onPress={onClose} style={styles.secondaryBtn}>
              <Text style={styles.secondaryBtnLabel}>Close</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { backgroundColor: 'white', borderRadius: 24, padding: 24, width: '90%', maxWidth: 360, alignItems: 'center', elevation: 20 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', marginBottom: 20 },
  headerTitle: { fontSize: 18, fontWeight: '800', color: '#272756' },
  closeBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center' },
  barcodeWrapper: { padding: 15, backgroundColor: '#f8f9fb', borderRadius: 16, borderWidth: 1, borderColor: '#e2e8f0', marginBottom: 20, width: '100%', alignItems: 'center', justifyContent: 'center' },
  webviewContainer: { width: 280, height: 90, overflow: 'hidden' },
  webview: { backgroundColor: 'transparent', flex: 1 },
  barcodeText: { fontSize: 14, fontWeight: '600', color: '#64748b', marginTop: 5, letterSpacing: 2 },
  loadingText: { fontSize: 10, color: '#94a3b8', marginTop: 4 },
  detailsContainer: { width: '100%', alignItems: 'center', marginBottom: 24 },
  itemName: { fontSize: 17, fontWeight: '700', color: '#1e293b', textAlign: 'center' },
  skuBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#f1f5f9', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, marginTop: 4 },
  skuText: { fontSize: 12, fontWeight: '600', color: '#64748b' },
  priceText: { fontSize: 22, fontWeight: '900', color: '#ec5b13', marginTop: 8 },
  actionsContainer: { width: '100%' },
  btnRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  btn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, height: 48, borderRadius: 12 },
  imageBtn: { backgroundColor: '#ec5b13' },
  pdfBtn: { backgroundColor: '#272756' },
  disabledBtn: { opacity: 0.5 },
  btnLabel: { color: 'white', fontSize: 11, fontWeight: '700' },
  secondaryBtn: { width: '100%', height: 48, borderRadius: 12, borderWidth: 1.5, borderColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center' },
  secondaryBtnLabel: { color: '#64748b', fontSize: 14, fontWeight: '700' },
});
