import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

/**
 * Generates an HTML Delivery Challan and opens the system print dialog / share sheet.
 * @param {object} challan - The challan object
 * @param {object} profile - The business profile
 */
export async function printChallan(challan, profile) {
  const businessName   = profile?.name || 'Business';
  const businessGstin  = profile?.gstin || '';
  const businessEmail  = profile?.email || '';

  const challanNumber = challan.challanNumber || '—';
  const customerName  = challan.customerName  || '—';
  const date          = challan.date || new Date().toLocaleDateString();
  const status        = challan.status || 'draft';
  const vehicleMode   = challan.vehicleMode || '—';

  const statusColor = {
    delivered: '#16a34a', open: '#2563eb', draft: '#64748b'
  }[status.toLowerCase()] || '#64748b';

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; background: #fff; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }
    .brand { font-size: 28px; font-weight: 900; color: #262A56; letter-spacing: -1px; }
    .brand-sub { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 2px; margin-top: 2px; }
    .meta { text-align: right; }
    .meta h2 { font-size: 22px; font-weight: 900; color: #262A56; }
    .meta p { font-size: 12px; color: #64748b; margin-top: 2px; }
    .divider { border: none; border-top: 2px solid #f1f5f9; margin: 24px 0; }
    .info-row { display: flex; justify-content: space-between; margin-bottom: 32px; }
    .info-block h4 { font-size: 10px; text-transform: uppercase; letter-spacing: 1.5px; color: #94a3b8; font-weight: 700; margin-bottom: 6px; }
    .info-block p { font-size: 14px; font-weight: 700; color: #1e293b; }
    .info-block p.sub { font-size: 12px; color: #64748b; font-weight: 500; margin-top: 2px; }
    .status-badge {
      display: inline-block; padding: 4px 12px; border-radius: 999px;
      font-size: 10px; font-weight: 800; letter-spacing: 1px;
      text-transform: uppercase; background: ${statusColor}22; color: ${statusColor};
    }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #94a3b8; font-weight: 700;
         padding: 10px 12px; text-align: left; background: #f8fafc; border-bottom: 1px solid #e2e8f0; }
    th.right, td.right { text-align: right; }
    td { font-size: 13px; padding: 12px; color: #334155; border-bottom: 1px solid #f1f5f9; }
    td.name { font-weight: 700; color: #1e293b; }
    .footer { margin-top: 48px; text-align: center; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">${businessName}</div>
      ${businessGstin ? `<div class="brand-sub">GSTIN: ${businessGstin}</div>` : ''}
    </div>
    <div class="meta">
      <h2>DELIVERY CHALLAN</h2>
      <p>No: ${challanNumber}</p>
      <p>Date: ${date}</p>
      <br/>
      <span class="status-badge">${status}</span>
    </div>
  </div>

  <hr class="divider"/>

  <div class="info-row">
    <div class="info-block">
      <h4>Delivery To</h4>
      <p>${customerName}</p>
      ${challan.vehicleMode ? `<p class="sub">Mode: ${challan.vehicleMode}</p>` : ''}
    </div>
    <div class="info-block" style="text-align:right">
      <h4>Reference</h4>
      <p>${challanNumber}</p>
      <p class="sub">Transport Mode: ${vehicleMode}</p>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Item Name & Description</th>
        <th class="right">Quantity</th>
      </tr>
    </thead>
    <tbody>
      ${(challan.items || []).map((item, i) => `
        <tr>
          <td>${i + 1}</td>
          <td class="name">${item.name || '—'}<br/><span style="font-size:11px;color:#94a3b8;font-weight:500">${item.sku ? 'SKU: ' + item.sku : ''}</span></td>
          <td class="right">${item.quantity || 1} ${item.unit || 'Units'}</td>
        </tr>`).join('')
      }
    </tbody>
  </table>

  ${challan.notes ? `
  <div style="margin-top:32px;padding:16px;background:#f8fafc;border-radius:8px;border-left:3px solid #262A56">
    <div style="font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#94a3b8;font-weight:700;margin-bottom:4px">Notes</div>
    <p style="font-size:13px;color:#475569">${challan.notes}</p>
  </div>` : ''}

  <div class="footer">
    <p>This is a computer generated document.</p>
    <p style="margin-top:4px">Generated by ${businessName} • ZOXM Invoice</p>
  </div>
</body>
</html>
`;

  try {
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        UTI: '.pdf',
        mimeType: 'application/pdf',
      });
    } else {
      await Print.printAsync({ uri });
    }
  } catch (error) {
    console.error('Print error:', error);
    throw error;
  }
}
